/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import entity.City;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import main.Controller;

/**
 *
 * @author Krisztian
 */
public class CityConnPanel extends javax.swing.JPanel {

    /**
     * Creates new form CityConnPanel
     */
    public CityConnPanel() {
        initComponents();
        setGUI();
    }
    
    private void setGUI(){
        SetCmbBoxStart();
    }
    
    private void SetCmbBoxStart(){
     DefaultComboBoxModel model = new DefaultComboBoxModel();
        List<City> list = Controller.GetCities();
        for (City c : list) {
            model.addElement(c);
        }
        cmbStart.setModel(model);
    }
    
    private void SetCmbBoxDest(){
             DefaultComboBoxModel model = new DefaultComboBoxModel();
        List<City> list = Controller.GetNotP2PConnectedCities((City) cmbStart.getSelectedItem());
        for (City c : list) {
            model.addElement(c);
        }
        cmbDest.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrp = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cmbStart = new javax.swing.JComboBox();
        rbtnNew = new javax.swing.JRadioButton();
        rbtnDelete = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        cmbDest = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbRoutes = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();

        jLabel1.setText("Start city:");

        cmbStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStartActionPerformed(evt);
            }
        });

        btnGrp.add(rbtnNew);
        rbtnNew.setText("New");

        btnGrp.add(rbtnDelete);
        rbtnDelete.setText("Delete");

        jLabel2.setText("Destination city:");

        jLabel3.setText("Routes");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbStart, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbDest, 0, 155, Short.MAX_VALUE)
                    .addComponent(cmbRoutes, 0, 155, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtnNew)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnDelete))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnNew)
                    .addComponent(rbtnDelete))
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbRoutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnSave)
                .addContainerGap(217, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       City start = new City(0, 0, "test1");
       City dest = new City(0, 0, "test2");
       Controller.GetCitiesWhicHaveConn();
        
        //Controller.AddCityConn(start, dest);
       //Controller.GetP2PConnectedCities(start, dest);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cmbStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStartActionPerformed
        SetCmbBoxDest();
    }//GEN-LAST:event_cmbStartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrp;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbDest;
    private javax.swing.JComboBox cmbRoutes;
    private javax.swing.JComboBox cmbStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rbtnDelete;
    private javax.swing.JRadioButton rbtnNew;
    // End of variables declaration//GEN-END:variables
}
