/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.Graphics;
import java.util.ArrayList;
import java.util.List;
import main.Controller;
import main.ValueListener;

/**
 *
 * @author Krisztian
 */
public  class MapPanel extends javax.swing.JPanel implements ValueListener{
    private final Integer height=445;
    private final Integer width=600;
    private Integer TAB = 3;
    private List<ValueListener> listeners = new ArrayList<ValueListener>();

    /**
     * Creates new form MapPanel
     */
    public MapPanel() {
        this.setSize(width, height);
        initComponents();
    }
    

    @Override
    protected  void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        Controller.Draw(g,TAB);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 153));
        setMinimumSize(new java.awt.Dimension(600, 500));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        notifyListeners(evt.getX()-5, evt.getY()-5);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void OnSubmitted(Integer t) {
        TAB = t;
        this.repaint();
    }

    @Override
    public void PassCoordinates(Integer X, Integer Y) {
        throw new UnsupportedOperationException("Not supported yet."); 
    }
    
        public void addListener(ValueListener listener) {
        listeners.add(listener);
    }
    
        private void notifyListeners(Integer X, Integer Y) {
        for (ValueListener listener : listeners) {
            listener.PassCoordinates(X, Y);
        }
    }
}
