/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entity.City;
import entity.Route;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import main.Controller;
import main.ValueListener;

/**
 *
 * @author Krisztian
 */
public class RoutePanel extends javax.swing.JPanel {

    private final Integer height = 445;
    private final Integer width = 200;
    private List<ValueListener> listeners = new ArrayList<ValueListener>();

    public RoutePanel() {

        initComponents();
        this.setSize(width, height);

        cmbDestCity.setEnabled(false);
        
        SetStartComboBox();

    }
    
    public void addListener(ValueListener listener) {
        listeners.add(listener);
    }
    
        private void notifyListeners() {
        for (ValueListener listener : listeners) {
            listener.OnSubmitted(0);
        }
    }

    private void SetStartComboBox() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        List<City> list = Controller.GetCitiesWhicHaveConn();
        for (City c : list) {
            model.addElement(c);
        }
        cmbStartCity.setModel(model);
    }

    private void SetDestComboBox() {
        cmbDestCity.setEnabled(true);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        City c = (City) cmbStartCity.getSelectedItem();
        List<String> list = Controller.GetConnectedCities(c);
        for (String s : list) {
            model.addElement(s);
        }
        cmbDestCity.setModel(model);
    }

    private void SetRouteComboBox() {
        

        DefaultListModel model = new DefaultListModel();
        String startName = ((City)cmbStartCity.getSelectedItem()).getName();
        String destName = (String) cmbDestCity.getSelectedItem();
        List<Route> list = Controller.GetRoutes(startName, destName);
        for (Route r : list) {
            model.addElement(r);
        }
        
        jlist.setModel(model);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbStartCity = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbDestCity = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlist = new javax.swing.JList();

        setMaximumSize(new java.awt.Dimension(175, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Start city:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        cmbStartCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStartCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStartCityActionPerformed(evt);
            }
        });
        add(cmbStartCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 155, -1));

        jLabel2.setText("Destination city:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, -1, -1));

        cmbDestCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDestCityActionPerformed(evt);
            }
        });
        add(cmbDestCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 89, 155, -1));

        jLabel3.setText("Routes:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 127, -1, -1));

        jlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlistMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jlist);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, 155, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbStartCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStartCityActionPerformed
        SetDestComboBox();
        if(cmbDestCity.getSelectedObjects()!=null){
             SetRouteComboBox();
        }
    }//GEN-LAST:event_cmbStartCityActionPerformed

    private void cmbDestCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDestCityActionPerformed
        SetRouteComboBox();
    }//GEN-LAST:event_cmbDestCityActionPerformed

    private void jlistMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlistMouseReleased
        if(jlist.getSelectedValue()!=null){
           Controller.setRoutes((Route) jlist.getSelectedValue());
        }
        notifyListeners();
    }//GEN-LAST:event_jlistMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbDestCity;
    private javax.swing.JComboBox cmbStartCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList jlist;
    // End of variables declaration//GEN-END:variables
}
