/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import entity.City;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import main.Controller;

/**
 *
 * @author Krisztian
 */
public class RoutePanel extends javax.swing.JPanel {

    private final Integer height = 445;
    private final Integer width = 200;
    
    public RoutePanel() {
        this.setSize(width, height);

        initComponents();
        cmbDestCity.setEnabled(false);
        cmbRoutes.setEnabled(false);
        SetStartComboBox();
        
    }
    
    private void SetStartComboBox() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        List<City> list = Controller.GetCities();
        for (City c : list) {
            model.addElement(c);
        }
        cmbStartCity.setModel(model);        
    }
    
    private void SetDestComboBox() {
        cmbDestCity.setEnabled(true);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        List<City> list = Controller.GetCities();
        for (City c : list) {
            model.addElement(c);
        }
        cmbDestCity.setModel(model);                
    }
    
    private void SetListbox(){
        cmbRoutes.setEnabled(true);
                DefaultComboBoxModel model = new DefaultComboBoxModel();
        List<City> list = Controller.GetCities();
        for (City c : list) {
            model.addElement(c);
        }
        cmbRoutes.setModel(model); 

        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbStartCity = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbDestCity = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbRoutes = new javax.swing.JComboBox();

        jLabel1.setText("Start city:");

        cmbStartCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStartCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStartCityActionPerformed(evt);
            }
        });

        jLabel2.setText("Destination city:");

        cmbDestCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDestCityActionPerformed(evt);
            }
        });

        jLabel3.setText("Routes:");

        cmbRoutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoutesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbStartCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbDestCity, 0, 180, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cmbRoutes, 0, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbStartCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDestCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbRoutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbStartCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStartCityActionPerformed
        SetDestComboBox();
    }//GEN-LAST:event_cmbStartCityActionPerformed

    private void cmbDestCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDestCityActionPerformed
        SetListbox();
    }//GEN-LAST:event_cmbDestCityActionPerformed

    private void cmbRoutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoutesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoutesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbDestCity;
    private javax.swing.JComboBox cmbRoutes;
    private javax.swing.JComboBox cmbStartCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
